apiVersion: sync.rax.io/v1alpha1
kind: Nautobot
metadata:
  labels:
    app.kubernetes.io/name: nautobotop
    app.kubernetes.io/managed-by: kustomize
  name: nautobot-sample
spec:
  nautobotSecretRef:
    name: nautobot-secret
    namespace: nautobot
    usernameKey: username
    tokenKey: token
  nautobotServiceRef:
    name: nautobot-default
    namespace: nautobot
