apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openstack

resources:
  - eventbus/eventbus-default.yaml
  - eventbus/poddisruptionbudget-eventbus-default-pdb.yaml
  - serviceaccounts/serviceaccount-sensor-submit-workflow.yaml
