apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nautobot-target-proxy.fullname" . }}
  labels:
    {{- include "nautobot-target-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nautobot-target-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nautobot-target-proxy.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: http
          readinessProbe:
            tcpSocket:
              port: http
          env:
            - name: NAUTOBOT_URL
              value: {{ required "values.nautobot.url is required" .Values.nautobot.url | quote }}
            - name: NAUTOBOT_LOCATION
              value: {{ required "values.nautobot.location is required" .Values.nautobot.location | quote }}
            - name: UNDERSTACK_PARTITION
              valueFrom:
                configMapKeyRef:
                  name: {{ required "values.nautobot.clusterDataConfigMapRef.name is required" .Values.nautobot.clusterDataConfigMapRef.name | quote }}
                  key: {{ required "values.nautobot.clusterDataConfigMapRef.key is required" .Values.nautobot.clusterDataConfigMapRef.key | quote }}
            - name: NAUTOBOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ required "values.nautobot.tokenSecretRef.name is required" .Values.nautobot.tokenSecretRef.name | quote }}
                  key: {{ required "values.nautobot.tokenSecretRef.key is required" .Values.nautobot.tokenSecretRef.key | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
