{{- if .Values.enabled.ironic }}
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: openstack-ironic
spec:
  amqp:
    openstack:
      url: amqp://rabbitmq-server-0.rabbitmq-nodes.openstack.svc.cluster.local:5672/ironic
      jsonBody: true
      exchangeName: ironic
      exchangeType: topic
      exchangeDeclare:
        durable: true
      routingKey: 'ironic_versioned_notifications.info'
      queueDeclare:
        name: argo_notifications
        durable: true
        exclusive: false
        autoDelete: false
        noWait: true
      consume:
        consumerTag: "argo-events"
        autoAck: true
        exclusive: false
        noLocal: false
      auth:
        username:
          name: argo-ironic-user-credentials
          key: username
        password:
          name: argo-ironic-user-credentials
          key: password
{{- end }}
