{{- if .Values.k8sSecretsEventSource.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: k8s-openstack-secrets
  namespace: openstack
spec:
  template:
    serviceAccountName: k8s-openstack-events-secrets
  resource:
    keystone-automation-user-upsert:
      namespace: openstack
      group: ""
      version: v1
      resource: secrets
      eventTypes:
        - ADD
        - UPDATE
      filter:
        labels:
          - key: understack.rackspace.com/keystone-role
            operation: exists
          - key: understack.rackspace.com/keystone-user
            operation: exists
    keystone-automation-user-delete:
      namespace: openstack
      group: ""
      version: v1
      resource: secrets
      eventTypes:
        - DELETE
      filter:
        labels:
          - key: understack.rackspace.com/keystone-user
            operation: exists
{{- end }}
