apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "undersync.fullname" . }}
  labels:
    {{- include "undersync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "undersync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "undersync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: http
          env:
          - name: asn
            value: '{{ required "values.asn is required" .Values.asn }}'
          - name: RACK_ENV
            value: '{{ required "values.environment is required" .Values.environment }}'
          - name: SETTINGS_FILE
            value: '{{ .Values.settings.mount_path }}/{{ .Values.settings.settings_filename }}'
          - name: CLOUDS_FILE
            value: '{{ .Values.settings.mount_path }}/{{ .Values.settings.clouds_filename }}'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: {{ .Values.settings.mount_path }}
            name: settings
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: settings
        projected:
          defaultMode: 420
          sources:
          - secret:
              name: settings-file
          - secret:
              name: openstack-undersync
