# syntax=docker/dockerfile:1

ARG OPENSTACK_VERSION
FROM docker.io/openstackhelm/ironic:${OPENSTACK_VERSION}-ubuntu_jammy

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        genisoimage \
        isolinux \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache sushy-oem-idrac==5.0.0 proliantutils==2.16.2
