apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runbook-controller-role
  labels:
    app.kubernetes.io/name: ironicrunbook
    app.kubernetes.io/component: rbac
rules:
  # Runbook permissions
  - apiGroups:
      - baremetal.ironicproject.org
    resources:
      - ironicrunbooks
    verbs:
      - get
      - list
      - watch

  # Status update permissions
  - apiGroups:
      - baremetal.ironicproject.org
    resources:
      - ironicrunbooks/status
    verbs:
      - get
      - patch
      - update
