# Defaults: https://github.com/mariadb-operator/mariadb-operator/blob/main/deploy/charts/mariadb-operator/values.yaml

metrics:
  enabled: true

config:
  # stick with OpenStack's officially supported version
  mariadbDefaultVersion: "11.4"
  mariadbImage:
    repository: docker-registry1.mariadb.com/library/mariadb
    tag: 11.4.10
