---
all:
  children:
    nautobot:
      hosts:
        localhost:
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          nautobot_url: "{{ lookup('ansible.builtin.env', 'NAUTOBOT_URL', default='http://nautobot-default.nautobot.svc') }}"
          # use account token with sufficient creds
          nautobot_token: "{{ lookup('ansible.builtin.env', 'NAUTOBOT_TOKEN', default='0123456789abcdef0123456789abcdef01234567') }}"
