---
instance_tags:
  - name: "leaf a side"
    content_types:
      - "dcim.device"
    color: "f44336"
  - name: "leaf b side"
    content_types:
      - "dcim.device"
    color: "3f51b5"
  - name: "storage-a-side"
    content_types:
      - "dcim.device"
      - "ipam.prefix"
      - "dcim.interface"
      - "vni_custom_model.ucvni"
      - "ipam.vrf"
    color: "f44336"
  - name: "storage-b-side"
    content_types:
      - "dcim.device"
      - "ipam.prefix"
      - "dcim.interface"
      - "vni_custom_model.ucvni"
      - "ipam.vrf"
    color: "3f51b5"
  - name: "partition"
    content_types:
      - "ipam.namespace"
      - "ipam.prefix"
      - "vni_custom_model.ucvni"
    color: "2196f3"
  - name: "site"
    content_types:
      - "ipam.namespace"
      - "ipam.prefix"
      - "vni_custom_model.ucvni"
    color: "ff9800"
  - name: "openstack-subnet-pool"
    content_types:
      - "ipam.prefix"
    color: "2196f3"
    description: "Prefix is used for OpenStack subnet pool allocation"
