{{- if .Values.enabled.cinder }}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: cinder-oslo-event
  annotations:
    workflows.argoproj.io/title: Process oslo_events for cinder volume type access
    workflows.argoproj.io/description: |+
      Triggers on the following Cinder Events:

      - volume_type_project.access.add
      - volume_type_project.access.remove

      Submits workflow using workflowtemplate/openstack-oslo-event

      Defined in `components/site-workflows/sensors/sensor-cinder-oslo-event.yaml`
spec:
  dependencies:
  - eventName: notifications
    eventSourceName: openstack-cinder
    name: oslo-event-type
    transform:
      # the event is a string-ified JSON so we need to decode it
      jq: '{body: (.body["oslo.message"] | fromjson)}'
    filters:
      dataLogicalOperator: "and"
      data:
        - path: body.event_type
          type: "string"
          # any of the values will trigger
          value:
            - "volume_type_project.access.add"
            - "volume_type_project.access.remove"
  template:
    serviceAccountName: sensor-submit-workflow
  triggers:
    - template:
        name: cinder-oslo-event
        k8s:
          operation: create
          parameters:
            # first parameter is the parsed oslo.message
            - dest: spec.arguments.parameters.0.value
              src:
                dataKey: body
                dependencyName: oslo-event-type
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: cinder-oslo-event-
                namespace: argo-events
              spec:
                arguments:
                  parameters:
                    - name: event-json
                workflowTemplateRef:
                  name: openstack-oslo-event
{{- end }}
