apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

helmCharts:
  - name: site-workflows
    namespace: argo-events
  - name: nautobot-token
    namespace: openstack
    valuesFile: nautobot-token-values.yaml

helmGlobals:
  chartHome: ../../workflows/
