apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nautobot
resources:
  - secrets.yaml
patches:
  - target:
      kind: HelmRelease
      name: understack-flux-nautobot
    patch: |
      - op: add
        path: /spec/values
        value:
          nautobot:
            ingress:
              enabled: true
              hostname: nautobot.example.com
            persistence:
              enabled: true
              storageClass: standard
              size: 5Gi
          celery:
            persistence:
              enabled: true
              storageClass: standard
              size: 10Gi
