apiVersion: v1
kind: ServiceAccount
metadata:
  name: neutron-router-flavor-operator
  namespace: openstack
  labels:
    app.kubernetes.io/name: neutron-router-flavor-operator
    app.kubernetes.io/component: controller
