# yaml-language-server: $schema=https://rackerlabs.github.io/understack/schema/openstack-sync/neutron-router-flavor.schema.json
---
apiVersion: neutron.understack.rackspace.net/v1alpha1
kind: NeutronRouterFlavor
metadata:
  name: svi
  labels:
    app.kubernetes.io/name: openstack-sync-plugins
    app.kubernetes.io/component: neutron-router-flavors
    app.kubernetes.io/part-of: openstack-sync
spec:
  cloudCredentialsRef:
    secretName: infrasetup
    cloudName: understack
  name: svi
  service_type: L3_ROUTER_NAT
  description: On-Fabric SVI Gateways
  service_profiles:
    - driver: neutron_understack.l3_router.svi.Svi
      description: On-Fabric SVI Gateways
