---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: nautobot-token-store
spec:
  provider:
    webhook:
      url: "http://nautobot-default.nautobot.svc.cluster.local/api/users/tokens/"
      method: POST
      headers:
        Content-Type: application/json
        Authorization: 'Token {{ .auth.apitoken }}'
      result:
        jsonPath: "$.key"
      secrets:
        - name: auth
          secretRef:
            name: nautobot-superuser
            namespace: nautobot
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: understack-workflows
  namespace: argo-events
  labels:
    external-secrets.io/type: webhook
spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: nautobot-token-store
  target:
    name: understack-workflows
    creationPolicy: Owner
    deletionPolicy: Delete
  data:
    - secretKey: token
      remoteRef:
        key: user-token
