---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ansible-workflow-template
  annotations:
    workflows.argoproj.io/title: Run arbitrary ansible playbook from the undercloud-rackspace repo
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/ansible-run.yaml`
spec:
  serviceAccountName: workflow
  templates:
  - name: ansible-run
    inputs:
      parameters:
      - name: playbook
        default: "nonexistent.yaml"
      - name: extra_vars
        default: "var=default"
      - name: inventory_file
        default: inventory/in-cluster/01-nautobot.yaml
      - name: check_mode
        default: "false"
    script:
      image: ghcr.io/rss-engineering/undercloud-nautobot/ansible:latest
      command: [bash]
      source: |
        #!/bin/bash
        set -e

        ARGS=(
          "{{ inputs.parameters.playbook }}"
          --extra-vars "{{ inputs.parameters.extra_vars }}"
          -i "{{ inputs.parameters.inventory_file }}"
          -vvv
        )

        if [ "{{ inputs.parameters.check_mode }}" = "true" ]; then
          ARGS+=(--check)
        fi

        ansible-playbook "${ARGS[@]}"
      env:
      - name: NAUTOBOT_TOKEN
        valueFrom:
          secretKeyRef:
            key: token
            name: nautobot-token
      envFrom:
      - configMapRef:
          name: cluster-metadata
          optional: false
