---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ansible-workflow-template
spec:
  parameters:
  - name: playbook
    default: "nonexistent.yaml"
  - name: extra_vars
    default: "var=default"
  - name: inventory_file
    default: inventory/in-cluster/01-nautobot.yaml
  templates:
  - name: ansible-run
    container:
      image: ghcr.io/rss-engineering/undercloud-nautobot/ansible:pr-533
      command: [ansible-playbook]
      args:
      - "{{ playbook }}"
      - --extra-vars
      - "{{ extra_vars }}"
      - "-i"
      - "{{ inventory_file }}"
      - "-vvv"
    env:
    - name: NAUTOBOT_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: nautobot-token
    envFrom:
    - configMapRef:
        name: cluster-metadata
        optional: false
