---
apiVersion: argoproj.io/v1alpha1
metadata:
  name: enroll-server
  annotations:
    workflows.argoproj.io/title: Perform server discovery and update Ironic
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/enroll-server.yaml`
kind: WorkflowTemplate
spec:
  serviceAccountName: workflow
  entrypoint: main
  volumes:
    - name: bmc-master
      secret:
        secretName: bmc-master
    - name: baremetal-manage
      secret:
        secretName: baremetal-manage
        items:
          - key: clouds.yaml
            path: clouds.yaml
  arguments:
    parameters:
      - name: ip_address
      - name: firmware_update
        value: "false"
      - name: raid_configure
        value: "true"
      - name: old_password
        value: calvin
      - name: external_cmdb_id
        value: ""
  templates:
    - name: main
      steps:
        - - name: enroll-server
            template: enroll-server
    - name: enroll-server
      container:
        image: ghcr.io/rackerlabs/understack/ironic-nautobot-client:latest
        command:
          - enrol-server
        args:
          - --ip-address
          - "{{workflow.parameters.ip_address}}"
          - --firmware-update
          - "{{workflow.parameters.firmware_update}}"
          - --raid-configure
          - "{{workflow.parameters.raid_configure}}"
          - --old-password
          - "{{workflow.parameters.old_password}}"
          - --external-cmdb-id
          - "{{workflow.parameters.external_cmdb_id}}"
        volumeMounts:
          - mountPath: /etc/openstack
            name: baremetal-manage
            readOnly: true
          - mountPath: /etc/bmc_master/
            name: bmc-master
            readOnly: true
        envFrom:
          - configMapRef:
              name: cluster-metadata
        env:
          - name: WF_NS
            value: "{{workflow.namespace}}"
          - name: WF_NAME
            value: "{{workflow.name}}"
          - name: WF_UID
            value: "{{workflow.uid}}"
          - name: OS_CLOUD
            value: understack
