apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - openstack
  - argo-events

helmCharts:
  - name: nautobot-token
    namespace: openstack
  - name: nautobot-token
    namespace: argo-events
  - name: nautobot-token
    namespace: undersync
