apiVersion: v1
kind: ConfigMap
metadata:
  name: ironic-dnsmasq
data:
  # external IP address of Ingress. Used to populate DNS A records for the
  # Understack components
  INGRESS_IP: 192.168.1.177
  # DNS zone suffix for wildcard A record pointing to INGRESS_IP
  DNS_ZONE: understack.local
  DNS_PORT: '53'
  # If you want to print rendered dnsmasq.conf in the logs
  # DEBUG_DNSMASQ_CONF: "yes"
