apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: argo-events
spec:
  template:
    spec:
      containers:
      - name: controller-manager
        args:
        - controller
        # run in namespaced mode and not cluster wide
        - --namespaced
        # configure the namespace where events actually run
        - --managed-namespace
        - argo-events
