---
apiVersion: v1
kind: Pod
metadata:
  name: "openstack-admin-client"
spec:
  restartPolicy: Always
  containers:
    - name: client
      image: ghcr.io/rackerlabs/understack/openstack-client:2025.2
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          trap 'echo "Received signal, shutting down..."; exit 0' TERM INT
          echo "OpenStack admin client pod starting..."
          while true; do
            sleep 30 &
            wait $!
          done
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
      volumeMounts:
        - name: pod-tmp
          mountPath: /tmp
      env:
        - name: OS_IDENTITY_API_VERSION
          value: "3"
      envFrom:
        - secretRef:
            name: keystone-keystone-admin
  volumes:
    - name: pod-tmp
      emptyDir: {}
