{{- $sso := .Values.understack.nautobot.sso.externalSecret -}}
{{- if $sso.enabled }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $sso.name }}
spec:
{{ toYaml $sso.spec | indent 2 }}
{{- end }}
