---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: cluster-data
    literals:
      - UNDERSTACK_PARTITION=""
    options:
      disableNameSuffixHash: true
