---

- name: Create Tags
  networktocode.nautobot.tag:
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    name: "{{ item.name }}"
    content_types: "{{ item.content_types }}"
    color: "{{ item.color }}"
  loop: "{{ instance_tags }}"
