{{- if or (eq (include "understack.isEnabled" (list $.Values.global "cluster_issuer")) "true") (eq (include "understack.isEnabled" (list $.Values.site "cluster_issuer")) "true") }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-%s" $.Release.Name "cluster-issuer" }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  destination:
    namespace: cert-manager
    server: {{ $.Values.cluster_server }}
  project: understack
  sources:
  - path: {{ include "understack.deploy_path" $ }}/cluster-issuer
    repoURL: {{ include "understack.deploy_url" $ }}
    targetRevision: {{ include "understack.deploy_ref" $ }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
{{- end }}
