ARG BASE=ghcr.io/rackerlabs/understack/python3.11.8-alpine3.19:latest
FROM ${BASE} AS builder

RUN --mount=type=cache,target=/var/cache/apk apk add --virtual build-deps gcc python3-dev musl-dev linux-headers
RUN --mount=type=cache,target=/root/.cache/pip pip install 'wheel==0.43.0'
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# copy in the code
COPY --chown=appuser:appgroup python/understack-workflows /tmp/understack/python/understack-workflows
COPY --chown=appuser:appgroup python/understack-flavor-matcher /tmp/understack/python/understack-flavor-matcher
# need netifaces built as a wheel
RUN --mount=type=cache,target=/root/.cache/pip pip wheel --wheel-dir /app/dist netifaces psutil==6.1.1
# build wheels and requirements.txt, skip hashes due to building of netifaces above which won't match
RUN --mount=type=cache,target=/root/.cache/uv \
    for proj in $(find /tmp/understack -name pyproject.toml); do \
      cd $(dirname ${proj}) && uv build --wheel --out-dir /tmp/wheels/; \
    done && \
    uv export --no-hashes -o /tmp/wheels/requirements.txt

FROM ${BASE} AS prod
LABEL org.opencontainers.image.description="UnderStack Workflows"
WORKDIR /app

RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=from=builder,source=/tmp/wheels,target=/tmp/wheels \
    /opt/venv/bin/python -m pip install --no-input --find-links /tmp/wheels/ \
      --only-binary netifaces psutils \
      -r /tmp/wheels/requirements.txt \
      understack-workflows

USER appuser
