---
- name: Create Custom Field Chassis MAC Address
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: MAC address advertised to LLDP neighbors (for switches only)
    label: Chassis MAC Address
    type: text
    key: chassis_mac_address
    required: false
    weight: 100
    content_types: dcim.device
    filter_logic: exact
    validation_regex: ^[0-9A-F][0-9A-F](:[0-9A-F][0-9A-F]){5}$

- name: Create Custom Field DHCP Relay IPv4 Address
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: >-
        For certain interface Roles, configure a "DHCP Helper" service on the
        router to forward DHCP requests from locally-connected clients to the
        DHCP server specified by this option. The value is an IPv4 address
        without the /prefixlen.
    label: DHCP Relay IPv4 Address
    type: text
    key: dhcp_relay_ipv4_address
    required: false
    weight: 100
    content_types:
      - dcim.interface
      - vni_custom_model.ucvni
    validation_regex: ^\d+\.\d+\.\d+\.\d+$
    filter_logic: exact

- name: Create Custom Field Tenant VLAN ID
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: >-
        VLAN ID visible to the Tenant, used in the dot1q tag when this VNI
        appears on a trunk port.  Normally different to the actual VLAN created
        on the switch - we use VLAN translation to gives the tenant a consistent
        VLAN ID across the whole fabric.
    label: Tenant VLAN ID
    type: integer
    key: tenant_vlan_id
    required: false
    weight: 100
    content_types:
      - vni_custom_model.ucvni
    validation_minimum: 1
    validation_maximum: 4096
    filter_logic: exact

- name: Create Custom Field External CMDB ID
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: External CMDB identifier for integration with external systems
    label: External CMDB ID
    key: external_cmdb_id
    type: text
    required: false
    weight: 100
    content_types: dcim.device
    filter_logic: exact

- name: Create Custom Field Interface Extras
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: Field to account for j2 items not indexed in NB by default
    label: interface details
    key: interface_config_items
    type: json
    required: false
    weight: 100
    content_types:
      - dcim.interface
    filter_logic: exact

- name: Create Custom Field Subnet Pool Name
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: Name of the OpenStack subnet pool to create from this prefix
    label: Subnet Pool Name
    key: subnet_pool_name
    type: text
    required: false
    weight: 100
    content_types:
      - ipam.prefix
    filter_logic: exact

- name: Create Custom Field Subnet Pool Default Prefixlen
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: Default prefix length for subnets created from this pool
    label: Default Prefixlen
    key: subnet_pool_default_prefixlen
    type: integer
    required: false
    weight: 100
    content_types:
      - ipam.prefix
    validation_minimum: 1
    validation_maximum: 32
    filter_logic: exact

- name: Create Custom Field Subnet Pool Min Prefixlen
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: Minimum prefix length for subnets created from this pool
    label: Min Prefixlen
    key: subnet_pool_min_prefixlen
    type: integer
    required: false
    weight: 100
    content_types:
      - ipam.prefix
    validation_minimum: 1
    validation_maximum: 32
    filter_logic: exact

- name: Create Custom Field Subnet Pool Max Prefixlen
  networktocode.nautobot.custom_field:
    state: present
    url: "{{ nautobot_url }}"
    token: "{{ nautobot_token }}"
    description: Maximum prefix length for subnets created from this pool
    label: Max Prefixlen
    key: subnet_pool_max_prefixlen
    type: integer
    required: false
    weight: 100
    content_types:
      - ipam.prefix
    validation_minimum: 1
    validation_maximum: 32
    filter_logic: exact
