name: Build OpenStack containers

on:
  push:
    tags:
      - v*
    branches:
      - main
    paths: &triggerpaths
      - "containers/cinder/**"
      - "containers/glance/**"
      - "containers/horizon/**"
      - "containers/ironic/**"
      - "containers/keystone/**"
      - "containers/neutron/**"
      - "containers/nova/**"
      - "containers/octavia/**"
      - "containers/openstack-client/**"
      - "containers/placement/**"
      - "containers/skyline/**"
      - ".github/workflows/containers-openstack.yaml"
      - ".github/workflows/build-container-reuse.yaml"
      - "python/**"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths: *triggerpaths
  workflow_dispatch:
  merge_group:
    types: [checks_requested]

jobs:
  openstack:
    strategy:
      matrix:
        project:
          - cinder
          - glance
          - horizon
          - keystone
          - octavia
          - openstack-client
          - skyline
    uses: ./.github/workflows/build-container-reuse.yaml
    secrets: inherit
    with:
      container_name: ${{ matrix.project }}
      dockerfile_path: containers/${{ matrix.project }}/Dockerfile
      build_args: OPENSTACK_VERSION=2025.2
      latest_name: "2025.2"

  placement:
    uses: ./.github/workflows/build-container-reuse.yaml
    secrets: inherit
    with:
      container_name: placement
      dockerfile_path: containers/placement/Dockerfile
      build_args: OPENSTACK_VERSION=2026.1
      latest_name: "2026.1"

  nova:
    uses: ./.github/workflows/build-container-reuse.yaml
    secrets: inherit
    with:
      container_name: nova
      dockerfile_path: containers/nova/Dockerfile
      build_args: OPENSTACK_VERSION=2026.1
      latest_name: "2026.1"

  neutron:
    uses: ./.github/workflows/build-container-reuse.yaml
    secrets: inherit
    with:
      container_name: neutron
      dockerfile_path: containers/neutron/Dockerfile
      build_args: OPENSTACK_VERSION=2026.1
      latest_name: "2026.1"

  ironic:
    uses: ./.github/workflows/build-container-reuse.yaml
    secrets: inherit
    with:
      container_name: ironic
      dockerfile_path: containers/ironic/Dockerfile
      build_args: OPENSTACK_VERSION=2026.1
      latest_name: "2026.1"
      target: final
