name: Releases
on:
  push:
    tags:
      - "understackctl/v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  packages: write
  id-token: write
  issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version-file: 'go/understackctl/go.mod'
          cache-dependency-path: 'go/understackctl/go.sum'
          cache: true

      - name: Install dependencies
        run: sudo apt-get install -y sed grep

      - name: Build and Package
        working-directory: go/understackctl
        run: |
          make build-all package-all checksums

      - name: Upload release artifacts
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          make_latest: false
          files: |
            go/understackctl/build/*.zip
            go/understackctl/build/*.tar.gz
            go/understackctl/build/checksums.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
